---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present

- name: Set limits.d/nofile.conf
  ansible.builtin.copy:
    src: nofile.conf
    dest: /etc/security/limits.d/nofile.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable compress on logrotate
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^#compress'
    line: 'compress'
    state: present

- name: Install common tools
  tags: swinst
  apt:
    name:
      - unzip
      - docker.io
    update_cache: yes

- name: systctl
  tags: sysctl
  shell:
    cmd: sysctl -w vm.max_map_count=262144
  register: resolvectl_status
