---

- name: Ensure Nomad directories
  tags: nomad
  file:
    path: "{{ item.dir }}"
    #owner: nomad
    #group: nomad
    state: directory
    mode: '0755'
  loop:
    - { dir: '/opt/nomad' }
    - { dir: '/opt/cni' }
    - { dir: '/opt/cni/bin' }
    - { dir: '/opt/crate' }
    - { dir: '/opt/crate/config' }
    - { dir: '/etc/nomad.d' }

- name: Ensure crateDB config files for demo purpose of local volume
  tags: cratedb
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
   # owner: nomad
   # group: nomad
    mode: 0644
  loop:
    - { src: 'crate.yml', dest: '/opt/crate/config/' }
    - { src: 'log4j2.properties', dest: '/opt/crate/config/' }
  notify: restart nomad

- name: Install Nomad 1.6.1
  tags: nomad
  unarchive:
    src: https://releases.hashicorp.com/nomad/1.6.1/nomad_1.6.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/nomad

- name: Install unit file to systemd
  tags: nomad
  ansible.builtin.copy:
    src: nomad.service
    dest: /etc/systemd/system/nomad.service
    #owner: nomad
    #group: nomad
    mode: 0644

- name: Configure systemd to use service
  tags: nomad
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: nomad.service
  notify: restart nomad

- name: Template Nomad config file
  tags: nomad
  template:
    dest: /etc/nomad.d/nomad.hcl
    src: nomad.hcl.j2
    #owner: nomad
    #group: nomad
    mode: '0640'
    lstrip_blocks: yes
    trim_blocks: no
  notify: restart nomad
  ignore_errors: yes ### ATM I ignore this

- name: Install CNI Plugins
  tags: nomad
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
    dest: /opt/cni/bin
    remote_src: true
