# Install required Ansible Collections and Roles
# https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
# https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file

collections:

  - name: hetzner.hcloud
    version: "1.6.0"

  - name: community.hashi_vault
    version: "2.2.0"

roles:

  - name: 0x0i.systemd
    version: "v0.3.5"
