---

- name: netplan generate
  command:
    argv:
      - /lib/netplan/generate

- name: resolvectl reload
  command:
    argv:
      - resolvectl
      - reload

- name: restart nomad
  ansible.builtin.systemd:
    daemon_reload: yes
    name: nomad
    state: restarted

- name: restart consul
  ansible.builtin.systemd:
    daemon_reload: yes
    name: consul
    state: restarted
